# Site settings
title: Gavin Eke
description: Gavin Eke
baseurl: /
url: "https://gavineke.com/"
enforce_ssl: gavineke.com

# User settings
username: Gavin Eke
user_title: Cyber Security Engineer
twitter_username: gavineke
linkedin_username: gavineke
github_username: gavineke
blog: "https://scripting.rocks/"

# Other
exclude: ['package.json', 'src' , 'node_modules']
