# Site settings
title: Gavin Eke
description: Gavin Eke
baseurl: /
url: "https://gavineke.com/"
enforce_ssl: gavineke.com

# User settings
username: Gavin Eke
user_title: Cloud Infrastructure Specialist
twitter_username: gavineke
linkedin_username: gavineke
github_username: gavineke

# Google-analytics
google-analytics:
  id: "UA-98430810-4"

exclude: ['package.json', 'src' , 'node_modules']
